### ISSUE TITLE
Check the Discord Documentation Before Copyrighting a script

### ISSUE THREAD

**Issue by ZelliDev** [zafross/NitroGiftGeneratorAndChecker#11]
Well Basically your script is copied from somes populars nitros gens. 

You claim you can check up to 500 nitros by minute, without proxy. 

The problem here, you'll be rate limited. If you read correctly the documentation, you'll see that 1 req / 1 sec is the rate of that API.

Next time before considering creating a script, you should consider first, to read the api correctly

**Comment by Stanley-GF** [comment]
zelly, stfu dumb skiddo.
