### ISSUE TITLE
program immediatley closes after startup

### ISSUE THREAD

**Issue by Muhavaux33** [zafross/NitroGiftGeneratorAndChecker#12]
Title says it all. program is not starting

**Comment by Dazz05** [comment]
Yes, i have the same problem, any program i need to download for debug?

**Comment by Dazz05** [comment]
o wait i found the problem of your program, its the api problem, u can only request 1 in a sec.

**Comment by cheslin23t** [comment]
Solution: have your cmd in same directory. Then run this (With python installed)

py start.py
