### ISSUE TITLE
FLIPPING TOKEN GRABBER GUYS DONT USE LOOK AT THIS 

### ISSUE THREAD

**Issue by scienceX-web** [zafross/NitroGiftGeneratorAndChecker#14]
[](url)
![image](https://user-images.githubusercontent.com/77831748/108620299-31726980-7466-11eb-939c-17cca417da46.png)

**Comment by scienceX-web** [comment]
dont use it
report this man
trying to steal peoples discord tokens

**Comment by NotSwaraj** [comment]
Um i mean dont use this cause its both skidded and shitty ratelimits BUT its not a token grabber

**Comment by Rileyuwu** [comment]
This guy is actually a clown he literally copy pasted the code and copy pasted the logger also KEK.

**Comment by TKperson** [comment]
I agree on the don't-use-it part. But where is the token grabber, I don't see it in the code.

**Comment by NotSwaraj** [comment]
> I agree on the don't-use-it part. But where is the token grabber, I don't see it in the code.

Yeah, but just don't use it in General

**Comment by stop-bark** [comment]
there is literally no logger clowns

**Comment by NotSwaraj** [comment]
Ikr bruh

**Comment by shape1234** [comment]
im confused will my discord account be gone or not
who shall i agree with

**Comment by NotSwaraj** [comment]
> im confused will my discord account be gone or not
> who shall i agree with

Just don't use it, its trash and it ratelimits HOWEVER its not a logger as its open source

**Comment by Psycho649** [comment]
Its not. There is no whatsoever token logger in this
