### ISSUE TITLE
tysm for logging my token and mass dming, unfriending, leaving servers from my account.

### ISSUE THREAD

**Issue by nichevulcan20** [zafross/NitroGiftGeneratorAndChecker#19]
I lose my friends. Moral of the story- im gay who was greedy.

**Comment by NotSwaraj** [comment]
We have the smartest man right here.

**Comment by Nexuzzzz** [comment]
> I lose my friends. Moral of the story- im gay who was greedy.

no, you infected yourself lol. This script doesn't crack ur account ya dumbass

**Comment by Fury7777** [comment]
I dont think its a token logger maybe you ran some other thing and got token logged
