### ISSUE TITLE
Broken Py File?

### ISSUE THREAD

**Issue by KOHISTORIAN** [zafross/NitroGiftGeneratorAndChecker#5]
For some odd reason the Py file wont open, ive tried Pyw, restarting and a few other methods but can't seem to find a working one.

Hoping I could recieve some assistance, it'd of course be much appreciated.

Sincerely, K.O

**Comment by me-rgb** [comment]
Hello! I'm a 1/2 decent python programmer xD. If you look in the code, you have to open a txt file that isn't there. Working version:
[ConfusedHarmlessSeahorse.zip](https://github.com/Zafros56/NitroGiftGeneratorAndChecker/files/5711059/ConfusedHarmlessSeahorse.zip)

**Comment by me-rgb** [comment]
Don't ask about the name...

**Comment by pmim** [comment]
I was trying to do the same thing and I didn't succeed, Mostly because I don't know what I am doing. I made the txt document, edited the .py file then removed the readme from the folder but it still doesn't work... help

**Comment by NotSwaraj** [comment]
> Hello! I'm a 1/2 decent python programmer xD. If you look in the code, you have to open a txt file that isn't there. Working version:
> [ConfusedHarmlessSeahorse.zip](https://github.com/Zafros56/NitroGiftGeneratorAndChecker/files/5711059/ConfusedHarmlessSeahorse.zip)

You don't seem like 'decent! Your OP
(If you get what sarcasm is than good for you Mr shitty programmer) #
